### ISSUE TITLE
Serial 2 port not working with esp32 espresif board newest includes

### ISSUE THREAD

**Issue by Jeriomas** [sparkfun/SparkFunDMX#23]
Hello, 

Maybe someone has encountered such a problem that after updating esp32 boards includes from 2.0.9 to 3.2.0 and serial 2 port stop working? Maybe something changed in the includes and the library needs to be changed?

**Comment by timthomassen** [comment]
I also seem to be running into this issue. I'm trying to run the first example, but I'm getting the following errors:

```
c:\Users\Tim\Documents\Arduino\libraries\SparkFun_DMX_Shield_Library\src\SparkFunDMX.cpp: In member function 'void SparkFunDMX::setComDir(bool)':
c:\Users\Tim\Documents\Arduino\libraries\SparkFun_DMX_Shield_Library\src\SparkFunDMX.cpp:55:28: error: no matching function for call to 'HardwareSerial::flush(bool)'
     _dmxSerial->flush(false);
                            ^
In file included from C:\Users\Tim\AppData\Local\Arduino15\packages\SparkFun\hardware\esp32\1.0.1\cores\esp32/Arduino.h:154:0,
                 from c:\Users\Tim\Documents\Arduino\libraries\SparkFun_DMX_Shield_Library\src\SparkFunDMX.h:19,
                 from c:\Users\Tim\Documents\Arduino\libraries\SparkFun_DMX_Shield_Library\src\SparkFunDMX.cpp:17:
C:\Users\Tim\AppData\Local\Arduino15\packages\SparkFun\hardware\esp32\1.0.1\cores\esp32/HardwareSerial.h:65:10: note: candidate: virtual void HardwareSerial::flush()
     void flush(void);
          ^
C:\Users\Tim\AppData\Local\Arduino15\packages\SparkFun\hardware\esp32\1.0.1\cores\esp32/HardwareSerial.h:65:10: note:   candidate expects 0 arguments, 1 provided
c:\Users\Tim\Documents\Arduino\libraries\SparkFun_DMX_Shield_Library\src\SparkFunDMX.cpp: In member function 'bool SparkFunDMX::update()':
c:\Users\Tim\Documents\Arduino\libraries\SparkFun_DMX_Shield_Library\src\SparkFunDMX.cpp:150:36: error: no matching function for call to 'HardwareSerial::flush(bool)'
             _dmxSerial->flush(false);
                                    ^
In file included from C:\Users\Tim\AppData\Local\Arduino15\packages\SparkFun\hardware\esp32\1.0.1\cores\esp32/Arduino.h:154:0,
                 from c:\Users\Tim\Documents\Arduino\libraries\SparkFun_DMX_Shield_Library\src\SparkFunDMX.h:19,
                 from c:\Users\Tim\Documents\Arduino\libraries\SparkFun_DMX_Shield_Library\src\SparkFunDMX.cpp:17:
C:\Users\Tim\AppData\Local\Arduino15\packages\SparkFun\hardware\esp32\1.0.1\cores\esp32/HardwareSerial.h:65:10: note: candidate: virtual void HardwareSerial::flush()
     void flush(void);
          ^
C:\Users\Tim\AppData\Local\Arduino15\packages\SparkFun\hardware\esp32\1.0.1\cores\esp32/HardwareSerial.h:65:10: note:   candidate expects 0 arguments, 1 provided
c:\Users\Tim\Documents\Arduino\libraries\SparkFun_DMX_Shield_Library\src\SparkFunDMX.cpp:155:50: error: no matching function for call to 'HardwareSerial::read(uint8_t [513], uint16_t&)'
         _dmxSerial->read(_dmxBuffer, _numChannels);
                                                  ^
In file included from C:\Users\Tim\AppData\Local\Arduino15\packages\SparkFun\hardware\esp32\1.0.1\cores\esp32/Arduino.h:154:0,
                 from c:\Users\Tim\Documents\Arduino\libraries\SparkFun_DMX_Shield_Library\src\SparkFunDMX.h:19,
                 from c:\Users\Tim\Documents\Arduino\libraries\SparkFun_DMX_Shield_Library\src\SparkFunDMX.cpp:17:
C:\Users\Tim\AppData\Local\Arduino15\packages\SparkFun\hardware\esp32\1.0.1\cores\esp32/HardwareSerial.h:64:9: note: candidate: virtual int HardwareSerial::read()
     int read(void);
         ^
C:\Users\Tim\AppData\Local\Arduino15\packages\SparkFun\hardware\esp32\1.0.1\cores\esp32/HardwareSerial.h:64:9: note:   candidate expects 0 arguments, 2 provided
exit status 1

Compilation error: exit status 1
```
